PATH := ~/.solc-select/artifacts/solc-0.8.34:$(PATH)
certora-beacon :; PATH=${PATH} certoraRun certora/Beacon.conf$(if $(rule), --rule $(rule),)$(if $(results), --wait_for_results all,)
certora-controller :; PATH=${PATH} certoraRun certora/Controller.conf$(if $(rule), --rule $(rule),)$(if $(results), --wait_for_results all,)
certora-general-facet-% :; PATH=${PATH} certoraRun certora/facets/general-$*.conf$(if $(rule), --rule $(rule),)$(if $(results), --wait_for_results all,)
certora-specific-facet-% :; PATH=${PATH} certoraRun certora/facets/specific-$*.conf$(if $(rule), --rule $(rule),)$(if $(results), --wait_for_results all,)
