name: Certora

on: [push, pull_request]

jobs:
  certora:
    name: Certora
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        diamond-pau:
          - beacon
          - general-facet-aave
          - specific-facet-aave
          - general-facet-aave-v4
          - general-facet-basin
          - general-facet-cctp
          - general-facet-centrifuge
          - general-facet-curve
          - general-facet-dai-usds
          - general-facet-dual-pool
          - general-facet-erc4626
          - general-facet-erc7540
          - general-facet-ethena
          - general-facet-farm
          - general-facet-layer-zero
          - general-facet-maple
          - general-facet-merkl
          - general-facet-nfat-halo
          - general-facet-nfat-prime
          - general-facet-otc
          - general-facet-pendle
          - general-facet-psm
          - general-facet-psm3
          - general-facet-spark-vault
          - general-facet-superstate
          - general-facet-transfer-asset
          - general-facet-uniswap-v3
          - general-facet-uniswap-v4
          - general-facet-usds
          - general-facet-weeth
          - general-facet-wrap-proxy-eth
          - general-facet-wsteth

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jre

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Solc Select 0.8.34
        run: solc-select install 0.8.34

      - name: Install Certora
        run: pip3 install certora-cli-beta

      - name: Verify ${{ matrix.diamond-pau }}
        run: make certora-${{ matrix.diamond-pau }} results=1
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
